### ISSUE TITLE
Add conda-forge package

### ISSUE THREAD

**Issue by constantinpape** [inferno-pytorch/firelight#2]

**Comment by constantinpape** [comment]
I will look into this soon, shouldn't be too difficult to make a conda recipe for this.
@imagirom Are there any special dependencies apart from tensorboardX?

**Comment by imagirom** [comment]
Cool!
There is not even a tensorboardX dependency, the main thing the library provides are mappings between pytorch tensors. All dependencies should be in setup.py, though I have not checked which versions are really required.

**Comment by constantinpape** [comment]
Ok, dependencies look very manageable :).

**Comment by constantinpape** [comment]
Started with the conda-forge recipe here:
https://github.com/inferno-pytorch/staged-recipes/blob/master/recipes/firelight/meta.yaml
There are just a few minor things that need to be changed / clarified:
- We need a release to have a tarball that conda forge can download. @imagirom if you don't mind I would go ahead and make release 0.1.0.
- What are the constraints on the python version? I guess python 2 is not supported, what about 3.5?
- Any constraints on the pytorch version? >=0.4 ?

**Comment by imagirom** [comment]
Nice! Regarding the questions:
- You can go ahead with the release.
- Python has to be >= 3.6, because I use f-strings everywhere (not sure if there are more reasons)
- Yep, pytorch >= 0.4 (only briefly checked 1.0, gives some deprecation warning but seems to work).

**Comment by constantinpape** [comment]
Ok, I made the PR to conda-forge:
https://github.com/conda-forge/staged-recipes
Still need to fix some issues thoguh....

**Comment by constantinpape** [comment]
Issues are spurious and the recipe is good to merge.
@imagirom please confirm if you want to be added as recipe maintainer or let
me know if I should remove you from the maintainer list.

**Comment by imagirom** [comment]
Please add me as a recipe maintainer. Thanks a lot for setting this up!

**Comment by constantinpape** [comment]
Please confirm that you want to be added as maintainer in the conda-forge PR too ;)
https://github.com/conda-forge/staged-recipes/pull/7373

**Comment by imagirom** [comment]
Done. Sorry, I missed you asking for that there.

**Comment by constantinpape** [comment]
No worries.
Package was merged and is on `conda-forge` now :).
